USE shopee;
DROP FUNCTION IF EXISTS Func_Valid_name;
DROP FUNCTION IF EXISTS Exists_Admin;

DELIMITER //
CREATE FUNCTION Func_Valid_name(s VARCHAR(255))
    RETURNS BOOLEAN
    DETERMINISTIC
BEGIN
    IF CHAR_LENGTH(s) <= 3 THEN
        RETURN FALSE;
    END IF;

    RETURN TRUE;
END //
DELIMITER ;


DELIMITER //
CREATE FUNCTION Exists_Admin(in_admin_usr VARCHAR(20))
    RETURNS BOOLEAN
    DETERMINISTIC
BEGIN
    RETURN EXISTS (SELECT 1 FROM Admin WHERE username = in_admin_usr);
END //
DELIMITER ;